// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMi2aMdZ6CbUIN2m_sceG6kNxmq0EsiGk',
    appId: '1:785133298004:web:a624794449d06f5dc868c1',
    messagingSenderId: '785133298004',
    projectId: 'hospital-f3ac8',
    authDomain: 'hospital-f3ac8.firebaseapp.com',
    storageBucket: 'hospital-f3ac8.firebasestorage.app',
    measurementId: 'G-WY7S4C600G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg8l5fTs5MTchWzmoiA4BKGQfuhKub1J8',
    appId: '1:785133298004:android:67f64c2719ded4c9c868c1',
    messagingSenderId: '785133298004',
    projectId: 'hospital-f3ac8',
    storageBucket: 'hospital-f3ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFw-3pE34kuHaza4kLwiKQl3GiPZ9J4Ws',
    appId: '1:785133298004:ios:59c207a9ead04007c868c1',
    messagingSenderId: '785133298004',
    projectId: 'hospital-f3ac8',
    storageBucket: 'hospital-f3ac8.firebasestorage.app',
    iosBundleId: 'com.example.hospital1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFw-3pE34kuHaza4kLwiKQl3GiPZ9J4Ws',
    appId: '1:785133298004:ios:59c207a9ead04007c868c1',
    messagingSenderId: '785133298004',
    projectId: 'hospital-f3ac8',
    storageBucket: 'hospital-f3ac8.firebasestorage.app',
    iosBundleId: 'com.example.hospital1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMi2aMdZ6CbUIN2m_sceG6kNxmq0EsiGk',
    appId: '1:785133298004:web:645c3f3e78b7d4f2c868c1',
    messagingSenderId: '785133298004',
    projectId: 'hospital-f3ac8',
    authDomain: 'hospital-f3ac8.firebaseapp.com',
    storageBucket: 'hospital-f3ac8.firebasestorage.app',
    measurementId: 'G-8ZQ7EQQQ30',
  );
}
